# Generated by Django 4.2.7 on 2024-11-27 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.customers'),
        ),
    ]
