# Generated by Django 4.2.7 on 2024-11-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_uploads_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(max_length=100)),
                ('base_colour', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
                ('product_display_name', models.CharField(max_length=200)),
            ],
        ),
    ]
